<div style="direction:rtl">
خب خب، درسته که نامپای ستون فقرات دیتا ساینیه، ولی ما کارامون رو با دست و چشم و پا انجام میدیم نه با خود ستون فقرات. برای همین تو این بخش زیاد تمرینای از جنس مساله نداریم و بیشتر تمرینامون حول تسلط به ابزار ها و متد های این کتابخونه است.
<div style="direction:rtl">
برای شروع، کتابخونه ی نامپای رو ایمپورت کنید.

In [ ]:
import numpy as np

<div style="direction:rtl">
یه آرایه ی متشکل از 10 تا صفر بسازید.

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<div style="direction:rtl">
یه آرایه ی متشکل از 10 تا یک بسازید.

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<div style="direction:rtl">
یه آرایه ی متشکل از 10 تا پنج بسازید.

In [ ]:
5 * np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

<div style="direction:rtl">
یه آرایه ی متشکل از اعداد ده تا پنجاه بسازید.

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

<div style="direction:rtl">
یه آرایه ی متشکل از اعداد زوج بین ده تا پنجاه بسازید.

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

<div style="direction:rtl">
یه ماتریس سه در سه با مقادیر 0 تا 8 بسازید.

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<div style="direction:rtl">
یه ماتریس سه در سه قطری بسازید.

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<div style="direction:rtl">
یه ماتریس سه در سه با اعداد رندوم بسازید.

In [ ]:
np.random.rand(3,3)

array([[0.28191081, 0.39566318, 0.97492219],
       [0.64601275, 0.93961334, 0.56236459],
       [0.49143156, 0.97446072, 0.75808196]])

<div style="direction:rtl">
یه ماتریس سه در سه با اعداد رندومی بسازید که به شکل نرمال حول 0 توزیع شده باشند.

In [ ]:
np.random.randn(3,3)

array([[-0.4855456 , -0.4218152 , -0.05204512],
       [ 1.10865501, -0.19935101, -1.22509664],
       [-1.80110109,  0.69397467, -0.50105574]])

<div style="direction:rtl">
با دو روش مختلف دقیقا ماتریس زیر رو بسازید.

In [ ]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
np.linspace(0.01,1.00,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

<div style="direction:rtl">
آرایه ای بسازید که شامل 20 تا عدد با فاصله های مساوی بین 0 و 1 باشه.

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

<div style="direction:rtl">
ابتدا ماتریس زیر را با نام mat بسازید و سپس تکه های خواسته شده از ماتریس در هر بخش را به دست آورید.

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3,4]

np.int64(20)

In [ ]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat[4,0:5]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[[0,2,4],0:5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[0:5,[0,2,4]]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25]])

In [ ]:
mat[[0,2,4],0:5][0:5,[0,2,4]]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

<div style="direction:rtl">
در باره ی axis ها(محور ها) در نامپای تحقیق کنید و axis دیفالت نامپای را معرفی کنید، سپس با کمک axis ها جمع سطر ها وستون های ماتریس را  به دست آورید.

<div style="direction:rtl">
axis دیفالت نامپای در جهت :...

<div style="direction:rtl">
جمع ستون ها :
(هم با متد هم با فانکشن)

<div style="direction:rtl">
حالا با کمک مفهومی که از محور ها در عملیات های نامپای فرا گرفته اید، سعی کنید با دستور concatenate دو ماتریس زیر را یک بار در جهت محور عمودی و یک بار در جهت محور افقی بهم بچسبانید.

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b = np.arange(1,10).reshape(3,3).transpose()
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

<div style="direction:rtl">
چسباندن در راستای افقی:

In [ ]:
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 1, 4, 7],
       [4, 5, 6, 2, 5, 8],
       [7, 8, 9, 3, 6, 9]])

<div style="direction:rtl">
چسباندن در راستای عمودی:

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

<div style="direction:rtl">

## موفق باشید.