In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4,5]

In [ ]:
my_array = np.array([1,2,3,4,5])

In [ ]:
print(my_list)
print(my_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
my_list

[1, 2, 3, 4, 5]

In [ ]:
my_array

array([1, 2, 3, 4, 5])

In [ ]:
my_matrix = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

In [ ]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
my_matrix.shape

(3, 3)

In [ ]:
my_array.shape

(5,)

### **arange**

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,11,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [ ]:
np.arange(-10,11)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
np.arange(-10,11,0.5)

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5,  10. ,  10.5])

In [ ]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

# **Zeros and Ones**

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
5 * np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# linspace

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

**Random**

In [ ]:
np.random.rand(5)

array([0.04909907, 0.97397822, 0.84131075, 0.47153577, 0.02046879])

In [ ]:
np.random.rand(4,5)

array([[0.20499119, 0.20677627, 0.04517445, 0.40279502, 0.95690983],
       [0.98397061, 0.88356854, 0.76131938, 0.10014467, 0.88298971],
       [0.75392457, 0.91858174, 0.00930646, 0.20741041, 0.57962267],
       [0.7114582 , 0.87186222, 0.12167709, 0.58596905, 0.67854543]])

In [ ]:
np.random.randn(5)

array([ 0.42263518, -0.80093971,  1.21545421,  0.43051537, -0.24522676])

In [ ]:
np.random.randn(5,5)

array([[-6.25118225e-01, -6.87270086e-01,  2.81702865e-01,
        -2.38837859e-02, -8.35524431e-01],
       [ 1.65911330e+00,  8.32316485e-01,  2.93875594e+00,
         3.92025206e-01, -1.12821092e-03],
       [ 4.00515074e-02, -1.64479781e+00, -4.48911764e-01,
        -2.09966166e+00,  2.88788981e-01],
       [ 3.68389286e-01,  2.42175179e-02,  1.05412637e+00,
         3.08977382e-01, -6.62742551e-01],
       [-8.99918142e-01, -1.38009764e+00,  7.37165267e-02,
        -1.05035620e+00,  1.09392668e+00]])

In [ ]:
np.random.randint(1,100)

11

In [ ]:
np.random.randint(1,100,10)

array([63, 61, 78,  1, 50, 58, 33, 40, 93, 95])

In [ ]:
np.random.randint(1,10,16).reshape(4,4)

array([[5, 5, 1, 9],
       [9, 9, 1, 9],
       [3, 1, 6, 5],
       [6, 1, 7, 8]])

# max,min,argmax,argmin

In [ ]:
randarr = np.random.randint(1,100,15)

In [ ]:
randarr

array([42, 67, 90, 83, 65, 51, 51, 16, 86, 18, 26, 42, 29, 88, 13])

In [ ]:
print(randarr.max())

90


In [ ]:
print(randarr.min())

13


In [ ]:
print(randarr.argmax())

2


In [ ]:
print(randarr.argmin())

14


**flatten**

In [ ]:
randmatrix = np.random.randint(1,100,25).reshape(5,5)
randmatrix

array([[54, 70, 80, 84, 14],
       [34, 66, 78, 25, 69],
       [47, 29, 80,  8, 89],
       [10, 46, 77, 86, 58],
       [71, 42, 75, 53, 73]])

In [ ]:
randmatrix.flatten()

array([54, 70, 80, 84, 14, 34, 66, 78, 25, 69, 47, 29, 80,  8, 89, 10, 46,
       77, 86, 58, 71, 42, 75, 53, 73])

**vstack,hstack,concatenate**

In [ ]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

In [ ]:
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.concatenate((A,B),axis=0) #vstack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((A,B),axis=1) #hstack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**dtype**

In [ ]:
randarr

array([42, 67, 90, 83, 65, 51, 51, 16, 86, 18, 26, 42, 29, 88, 13])

In [ ]:
randarr.dtype

dtype('int64')

In [ ]:
sample = np.array([1,2,3,4,5],dtype="int32")

In [ ]:
sample.dtype

dtype('int32')

In [ ]:
arr = np.array([1,2,3,4,5],dtype="float64")

In [ ]:
arr

array([1., 2., 3., 4., 5.])

**Numpy indexing and Selection**

In [ ]:
arr = np.arange(10,101,10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
print(arr[1])

20


In [ ]:
print(arr[-1])

100


In [ ]:
print(arr[7])

80


In [ ]:
arr[3:7]

array([40, 50, 60, 70])

In [ ]:
arr[0:4] = 0

In [ ]:
arr

array([  0,   0,   0,   0,  50,  60,  70,  80,  90, 100])

In [ ]:
arr_2d = np.arange(5,46,5).reshape(3,3)
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[0]

array([ 5, 10, 15])

In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
print(arr_2d[2][2])

45


In [ ]:
print(arr_2d[0][1])

10


In [ ]:
arr_2d[1][1:]

array([25, 30])

In [ ]:
arr_2d[0][0:2]

array([ 5, 10])

In [ ]:
arr_2d[1:3,1:3]

array([[25, 30],
       [40, 45]])

In [ ]:
arr_2d[1:3,1:3][0]

array([25, 30])

## Fancy Indexing

In [ ]:
arr = np.arange(1,101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
arr[[2,6]]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [ ]:
arr[:,[1,5]]

array([[ 2,  6],
       [12, 16],
       [22, 26],
       [32, 36],
       [42, 46],
       [52, 56],
       [62, 66],
       [72, 76],
       [82, 86],
       [92, 96]])

In [ ]:
#arr[2:6,4:8]
#arr[2:6,[4,5,6,7]]
#arr[[2,3,4,5],4:8]
arr[[2,3,4,5]][:,[4,5,6,7]]

array([[25, 26, 27, 28],
       [35, 36, 37, 38],
       [45, 46, 47, 48],
       [55, 56, 57, 58]])

In [ ]:
arr[3:7,[3,5,7]]

array([[34, 36, 38],
       [44, 46, 48],
       [54, 56, 58],
       [64, 66, 68]])

In [ ]:
arr[[2,4],[[3],[5]]]

array([[24, 44],
       [26, 46]])

In [ ]:
arr[[2,4],[[3],[5]]].transpose()

array([[24, 26],
       [44, 46]])

**Selection**

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
new_arr = arr > 5
new_arr.dtype

dtype('bool')

In [ ]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [ ]:
arr_2d = np.linspace(-3,3,9).reshape(3,3)
arr_2d

array([[-3.  , -2.25, -1.5 ],
       [-0.75,  0.  ,  0.75],
       [ 1.5 ,  2.25,  3.  ]])

In [ ]:
arr_2d[arr_2d>0]

array([0.75, 1.5 , 2.25, 3.  ])

In [ ]:
arr_2d[arr_2d<0]

array([-3.  , -2.25, -1.5 , -0.75])

In [ ]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
matrix[matrix%3==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [ ]:
len(matrix[matrix%3==0])

8

In [ ]:
matrix[matrix%3==0].sum()

np.int64(108)

In [ ]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
matrix.sum()

np.int64(325)

In [ ]:
matrix.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [ ]:
matrix.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
matrix.std()

np.float64(7.211102550927978)

In [ ]:
np.linspace(0,0.5,1000).std()

np.float64(0.14448197710571045)

In [ ]:
numbers = np.random.randint(1,1000,30)
numbers

array([893, 762, 766, 610, 739, 462, 471,  55, 747, 662, 563, 290, 868,
        89, 693, 350, 468, 963,  91, 239,  86, 401, 726, 357, 889,  68,
       430,  56, 256, 161])

In [ ]:
numbers.std()

np.float64(286.35643872628395)

Numpy Operations (Arithmetic)

In [ ]:
my_arr = np.arange(1,10)
my_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
your_arr = np.arange(-9,0)
your_arr

array([-9, -8, -7, -6, -5, -4, -3, -2, -1])

In [ ]:
my_arr + your_arr

array([-8, -6, -4, -2,  0,  2,  4,  6,  8])

In [ ]:
A = my_arr.reshape(3,3)
B = your_arr.reshape(3,3)

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B

array([[-9, -8, -7],
       [-6, -5, -4],
       [-3, -2, -1]])

In [ ]:
A + B

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [ ]:
my_arr - your_arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

In [ ]:
A-B

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
4 * my_arr

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [ ]:
my_arr * your_arr

array([ -9, -16, -21, -24, -25, -24, -21, -16,  -9])

In [ ]:
my_arr @ your_arr

np.int64(-165)

In [ ]:
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]


In [ ]:
A * B

array([[ -9, -16, -21],
       [-24, -25, -24],
       [-21, -16,  -9]])

In [ ]:
A @ B

array([[ -30,  -24,  -18],
       [ -84,  -69,  -54],
       [-138, -114,  -90]])

In [ ]:
np.dot(A,B)

array([[ -30,  -24,  -18],
       [ -84,  -69,  -54],
       [-138, -114,  -90]])

**Universal Array Functions**

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [ ]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [ ]:
np.max(arr)

np.int64(10)

In [ ]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [ ]:
scores = np.random.randint(0,20,30)
scores

array([16,  5, 19, 16, 16,  0, 10,  2, 13,  9, 18, 16,  2, 16,  9, 16, 10,
        0, 19,  1, 15,  1,  3, 10, 12,  0, 15, 17,  5,  4])

In [ ]:
scores[scores>10]

array([16, 19, 16, 16, 13, 18, 16, 16, 16, 19, 15, 12, 15, 17])

In [ ]:
len(scores[scores>10])/30

0.4666666666666667